### ISSUE TITLE
[meta] Release 0.5.0

### ISSUE THREAD

**Issue by trojanowski** [trojanowski/react-apollo-hooks#138]
I'm going to introduce a few breaking changes in the next release of react-apollo-hooks:

- [x] `useMutation` returns tuple with result data (#135, based on #93)
- [ ] use `setOptions` for updating query (#134)
- [ ] fix behavior of `getMarkupFromTree` (#65)

Please note that the first one has the most significant impact. The other ones are breaking only in some subtle scenarios.

**Comment by emadow** [comment]
Thanks for your work here. Really looking forward to this release!

**Comment by lukasluecke** [comment]
Also looking forward to the release 🚀  - is there any ETA for at least an experimental release? Tried building the PR-version myself but got some weird issues with apollo 😕

**Comment by SimenB** [comment]
Would be lovely to release the mutation change without waiting for the other PRs (if they're gonna take a week or more) 🙏

**Comment by trojanowski** [comment]
@SimenB I just published an alpha version of 0.5.0 with #135 (the mutation change) merged-in. It's available as `react-apollo-hooks@alpha`.

**Comment by SimenB** [comment]
That's awesome, thanks!

**Comment by evert-smit** [comment]
@trojanowski with `react-apollo-hooks@alpha`, I am getting an error using the format from the README in my project:

```js
function TasksWithMutation() {
  const toggleTask = useMutation(TOGGLE_TASK_MUTATION);

  return (
    <TaskList
      onChange={task => toggleTask({ variables: { taskId: task.id } })}
      tasks={data.tasks}
    />
  );
}
```
I've customized this example but the error running this example should be `toggleTask is not a function`.

Downgrading to @0.4.5 solved the error.

I haven't looked into it any further because of a lack of time right now, but thought I should let you know.

**Comment by lukasluecke** [comment]
@evert-smit You need to wrap `toggleTask` like `[toggleTask]` - this is exactly the change that #135 entails. The README will only be updated in master once it's merged there, but you can check out the README in the PR for the correct code.

**Comment by evert-smit** [comment]
Thanks! Sorry about that, should have noticed :)

**Comment by TimFL** [comment]
Are there any plans to finish this release up or is this project dead due to the (I hope soonish?) release of hooks in the official apollo client?

**Comment by trojanowski** [comment]
I decided to release version 0.5.0 with `useMutation` changes and fixes for TypeScript and Apollo Client 2.6.0. I didn't have time for #134 - if someone needs it and could continue the work, then I'd merge it (but maybe "@apollo/react-hooks" is a better alternative in that case). :)
